/**
 * German word list for ClueGrid.
 * 200+ common nouns in German suitable for a word-deduction game.
 */
export const DE_WORDS: readonly string[] = [
  // Natur & Umwelt
  "BERG", "FLUSS", "WALD", "WÜSTE", "OZEAN", "INSEL", "SCHLUCHT", "GLETSCHER",
  "VULKAN", "HÖHLE", "TAL", "SUMPF", "DSCHUNGEL", "KLIPPE", "RIFF", "DÜNE",
  "WIESE", "WASSERFALL", "GEYSIR", "LAGUNE", "TUNDRA", "SAVANNE", "PLATEAU",
  // Tiere
  "HAI", "ADLER", "LÖWE", "WOLF", "BÄR", "FALKE", "KOBRA", "PANTHER",
  "WAL", "KRABBE", "MOTTE", "PAPAGEI", "KRAKE", "BISON", "LUCHS", "OTTER",
  "REIHER", "HIRSCH", "ROBBE", "RABE", "FUCHS", "EULE", "ELCH", "PINGUIN",
  "SKORPION", "KÄFER", "PYTHON", "BÜFFEL", "CHAMÄLEON", "WALROSS",
  // Gegenstände & Werkzeuge
  "ANKER", "AMBOSS", "PFEIL", "AXT", "FASS", "GLOCKE", "KLINGE", "BOLZEN",
  "BRÜCKE", "BÜRSTE", "EIMER", "KANONE", "KETTE", "SCHORNSTEIN", "UHR",
  "KOMPASS", "KRONE", "KRISTALL", "DOLCH", "TROMMEL", "ZAUN", "FLASCHE",
  "TOR", "HAMMER", "HAKEN", "HORN", "KRUG", "SCHLÜSSEL", "LATERNE", "SCHLOSS",
  "SPIEGEL", "NETZ", "NADEL", "KUGEL", "ROHR", "PRISMA", "ROLLE", "PUMPE",
  "SEIL", "SEGEL", "SCHILD", "SIEB", "NAGEL", "FEDER", "STAB", "STEMPEL",
  "STATUE", "SCHWERT", "FACKEL", "FALLE", "TRESOR", "WAGEN", "RAD", "PFEIFE",
  "DRAHT", "SCHRAUBENSCHLÜSSEL", "BRET", "SCHAUFEL", "MEISSEL", "KOLBEN",
  // Orte & Gebäude
  "ABTEI", "ARENA", "DACHBODEN", "BANK", "SCHEUNE", "BASAR", "BUNKER", "SCHLOSS",
  "KELLER", "KAPELLE", "ZITADELLE", "KOLONIE", "HÜTTE", "DOCK", "VERLIES",
  "FABRIK", "BAUERNHOF", "FESTUNG", "HAFEN", "KRANKENHAUS", "HOTEL", "LEUCHTTURM",
  "VILLA", "MARKT", "MINE", "MUSEUM", "PALAST", "PIER", "HAFEN", "GEFÄNGNIS",
  "PYRAMIDE", "RANCH", "RUINE", "SCHULE", "SCHREIN", "STALL", "BAHNHOF",
  "TEMPEL", "TURM", "TUNNEL", "DORF", "LAGERHAUS", "BRUNNEN",
  // Essen & Trinken
  "APFEL", "SPECK", "BROT", "BUTTER", "KUCHEN", "BONBON", "KÄSE", "KIRSCHE",
  "SCHOKOLADE", "MOST", "KAFFEE", "SAHNE", "EI", "TRAUBE", "HONIG", "MARMELADE",
  "ZITRONE", "LIMETTE", "AHORN", "MELONE", "MILCH", "MINZE", "PILZ", "SENF",
  "OLIVE", "ZWIEBEL", "ORANGE", "PFIRSICH", "PFEFFER", "GURKE", "PFLAUME", "KARTOFFEL",
  "KÜRBIS", "REIS", "SALZ", "SOSSE", "GEWÜRZ", "STEAK", "ZUCKER", "TEE",
  "TOMATE", "VANILLE", "ESSIG", "WALNUSS", "WEIN", "HEFE",
  // Personen & Gesellschaft
  "AGENT", "SCHÜTZE", "KÜNSTLER", "BARON", "KAPITÄN", "KOCH", "OBERST",
  "DETEKTIV", "DIPLOMAT", "ARZT", "HERZOG", "ÄLTESTER", "KAISER", "INGENIEUR",
  "FORSCHER", "GENERAL", "WACHE", "HEROLD", "JÄGER", "RICHTER", "RITTER",
  "ANWALT", "HÄNDLER", "MÖNCH", "NAVIGATOR", "ADLIGER", "PFLEGERIN", "PILOT",
  "PIRAT", "DICHTER", "PRIESTER", "PRINZ", "KÖNIGIN", "RANGER", "MATROSE",
  "GELEHRTER", "SCOUT", "SENATOR", "SCHERIFF", "SOLDAT", "CHIRURG", "DIEB",
  "SCHURKE", "ZAUBERER",
  // Abstrakta & Konzepte
  "ABGRUND", "ALTER", "BÜNDNIS", "HINTERHALT", "BALANCE", "BLUT", "BINDUNG",
  "GRENZE", "CHAOS", "CODE", "VERTRAG", "KRISE", "FLUCH", "DÄMMERUNG",
  "TOD", "DEKRET", "UNTERGANG", "ECHO", "REICH", "RÄTSEL",
  "EXIL", "SCHICKSAL", "FLAMME", "FROST", "GEIST", "RUHM", "GRAB", "EHRE",
  "ILLUSION", "EISEN", "LEGENDE", "LICHT", "VERBINDUNG", "MASKE", "MISSION",
  "NACHT", "EID", "ORDNUNG", "URSPRUNG", "PAKT", "FRIEDEN", "PHANTOM", "PLAGE",
  "GIFT", "MACHT", "PROPHEZEIHUNG", "QUEST", "RELIKT", "RISS", "RITUAL",
  "RUNE", "ANSTURM", "SCHATTEN", "STILLE", "RAUCH", "SEELE", "QUELLE", "STURM",
  "SCHLAG", "THRON", "GEZEITEN", "ZEIT", "SPUR", "PROZESS", "WAHRHEIT", "UNION",
  "SCHLEIER", "LEERE", "KRIEG", "UHR", "WIND", "ZONE"
] as const;

export type DeWord = (typeof DE_WORDS)[number];
