/**
 * Indonesian word list for ClueGrid.
 * 200+ common nouns in Indonesian suitable for a word-deduction game.
 */
export const ID_WORDS: readonly string[] = [
  // Alam & Luar Ruangan
  "GUNUNG", "SUNGAI", "HUTAN", "GURUN", "SAMUDRA", "PULAU", "NGARAI", "GLETSER",
  "VOLKAN", "GUA", "LEMBAH", "RAWA", "RIMBA", "TEBING", "TERUMBU", "GUMUK",
  "PADANG", "AIRTERJUN", "GEYSER", "LAGUNA", "TUNDRA", "SAVANA", "DATARAN",
  // Hewan
  "HIU", "ELANG", "SINGA", "SERIGALA", "BERUANG", "ALAP", "KOBRA", "PANTER",
  "PAUS", "KEPITING", "NENGAT", "KAKATUA", "CUMI", "BISON", "LYNX", "BERANG",
  "BANGO", "RUSA", "FOK", "GAGAK", "RUBAH", "HANTU", "MOOSE", "PENGUIN",
  "AKREP", "KUMBANG", "PITON", "BANTENG", "BUNGLON", "MORSA",
  // Benda & Alat
  "JANGKAR", "LANDASAN", "PANAH", "KAPAK", "TONG", "LONCENG", "BILAH", "BAUT",
  "JEMBATAN", "SIKAT", "EMBER", "MERIAM", "RANTAI", "CEROBONG", "JAM",
  "KOMPAS", "MAHKOTA", "KRISTAL", "BELATI", "DRUM", "PAGAR", "LABU", "GERBANG",
  "PALU", "KAIT", "TANDUK", "GUCI", "KUNCI", "LENTERA", "GEMBOK",
  "CERMIN", "JARING", "JARUM", "BOLA", "PIPA", "PRISMA", "KATROL", "POMPA",
  "TALI", "LAYAR", "PERISAI", "SARINGAN", "PAKU", "PEGAS", "TONGKAT", "STEMPEL",
  "PATUNG", "PEDANG", "OBOR", "JEBAKAN", "BRANKAS", "GEROBAK", "RODA", "PLUIT",
  "KAWAT", "KUNCI", "PAPAN", "SEKOP", "PAHAT", "PISTON",
  // Tempat & Bangunan
  "BIARA", "ARENA", "LOTENG", "BANK", "LUMBUNG", "BAZAR", "BUNGKER", "KASTEL",
  "RUANGBAWAH", "KAPEL", "SITADELA", "KOLONI", "PONDOK", "DERMAGA", "PENJARA",
  "PABRIK", "PEKAN", "BENTENG", "PELABUHAN", "RUMAHSAKIT", "HOTEL", "MERCUSUAR",
  "VILLA", "PASAR", "TAMBANG", "MUSEUM", "ISTANA", "DERMAGA", "PELABUHAN", "PENJARA",
  "PIRAMID", "PETERNAKAN", "RUNTUHAN", "SEKOLAH", "KUIL", "KANDANG", "STASIUN",
  "KUIL", "MENARA", "TEROWONGAN", "DESA", "GUDANG", "SUMUR",
  // Makanan & Minuman
  "APEL", "BACON", "ROTI", "MENTEGA", "KUE", "PERMEN", "KEJU", "CERI",
  "COKELAT", "SIDER", "KOPI", "KRIM", "TELUR", "ANGGUR", "MADU", "SELAI",
  "LEMON", "LIMAU", "MAPLE", "MELON", "SUSU", "MINT", "JAMUR", "SAUS",
  "ZAITUN", "BAWANG", "JERUK", "PERSIK", "LADA", "ACAR", "PLUM", "KENTANG",
  "LABU", "NASI", "GARAM", "SAUS", "REMPAH", "BISTIK", "GULA", "TEH",
  "TOMAT", "VANILA", "CUKA", "KENARI", "WINE", "RAGI",
  // Orang & Masyarakat
  "AGEN", "PEMANAH", "SENIMAN", "BARON", "KAPTEN", "KOKI", "KOLONEL",
  "DETEKTIF", "DIPLOMAT", "DOKTER", "ADIPATI", "TETUA", "KAISAR", "INSINYUR",
  "PENJELAJAH", "JENDERAL", "PENJAGA", "BENTARA", "PEMBURU", "HAKIM", "KSATRIA",
  "PENGACARA", "PEDAGANG", "BIKSU", "NAVIGATOR", "BANGSAWAN", "PERAWAT", "PILOT",
  "BAJAKLAUT", "PENYAIR", "PENDETA", "PANGERAN", "RATU", "RANGER", "PELAUT",
  "SARJANA", "PRAMUKA", "SENATOR", "SYERIF", "PRAJURIT", "BEDAH", "PENCURI",
  "PENJAHAT", "PENYIHIR",
  // Konsep & Abstrak
  "JURANG", "USIA", "ALIANSI", "JEBAKAN", "KESEIMBANGAN", "DARAH", "IKATAN",
  "BATAS", "KEKACAUAN", "KODE", "KONTRAK", "KRISIS", "KUTUKAN", "FAJAR",
  "KEMATIAN", "KEPUTUSAN", "KEBINASAAN", "GEMA", "KERAJAAN", "TEKA",
  "PENGASINGAN", "TAKDIR", "API", "ES", "HANTU", "KEJAYAAN", "KUBURAN", "KEHORMATAN",
  "ILUSI", "BESI", "LEGENDA", "CAHAYA", "HUBUNGAN", "TOPENG", "MISI", "MALAM",
  "SUMPAH", "ATURAN", "ASAL", "PAKTA", "PERDAMAIAN", "FANTOM", "WABAH", "RACUN",
  "KEKUATAN", "RAMALAN", "PENCARIAN", "PUSAKA", "CELAH", "RITUAL", "RUNA", "SERBUAN",
  "BAYANGAN", "KEHENINGAN", "ASAP", "JIWA", "SUMBER", "BADAI", "SERANGAN", "TAKHTA",
  "PASANG", "WAKTU", "JEJAK", "SIDANG", "KEBENARAN", "PERSATUAN", "CADAR", "KOSONG",
  "PERANG", "ARLOJI", "ANGIN", "ZONA"
] as const;

export type IdWord = (typeof ID_WORDS)[number];
