/**
 * Italian word list for ClueGrid.
 * 200+ common nouns in Italian suitable for a word-deduction game.
 */
export const IT_WORDS: readonly string[] = [
  // Natura & All'aperto
  "MONTAGNA", "FIUME", "FORESTA", "DESERTO", "OCEANO", "ISOLA", "CANYON", "GHIACCIAIO",
  "VULCANO", "CAVERNA", "VALLE", "PALUDE", "GIUNGLA", "SCOGLIERA", "BARRIERA", "DUNA",
  "PRATO", "CASCATA", "GEYSER", "LAGUNA", "TUNDRA", "SAVANA", "ALTOPIANO",
  // Animali
  "SQUALO", "AQUILA", "LEONE", "LUPO", "ORSO", "FALCO", "COBRA", "PANTERA",
  "BALENA", "GRANCHIO", "FALENA", "PAPPAGALLO", "CALAMARO", "BISONTE", "LINCE", "LONTRA",
  "AIRONE", "CERVO", "FOCA", "CORVO", "VOLPE", "GUFO", "ALCE", "PINGUINO",
  "SCORPIONE", "COCCINELLA", "PITONE", "BUFALO", "CAMALEONTE", "VALRUSS",
  // Oggetti & Strumenti
  "ANCORA", "INCUDINE", "FRECCIA", "ACCETTA", "BARILE", "CAMPANA", "LAMA", "BULLONE",
  "PONTE", "SPAZZOLA", "SECCHIO", "CANNONE", "CATENA", "CAMINO", "OROLOGIO",
  "BUSSOLA", "CORONA", "CRISTALLO", "PUGNALE", "TAMBURO", "RECINZIONE", "FLACONE",
  "CANCELLO", "MARTELLO", "GANCIO", "CORNO", "GIARA", "CHIAVE", "LANTERNA", "SERRATURA",
  "SPECCHIO", "RETE", "AGO", "SFERA", "TUBO", "PRISMA", "PULEGGIA", "POMPA",
  "CORDA", "VELA", "SCUDO", "SETACCIO", "SPINA", "MOLLA", "BASTONE", "TIMBRO",
  "STATUE", "SPADA", "TORCIA", "TRAPPOLA", "CASSAFORTE", "VAGONE", "RUOTA", "FISCHIETTO",
  "FILO", "CHIAVE", "TAVOLA", "PALA", "SCALPELLO", "PISTONE",
  // Luoghi & Strutture
  "ABBAZIA", "ARENA", "SOFFITTA", "BANCA", "FIENILE", "BAZAR", "BUNKER", "CASTELLO",
  "CANTINA", "CAPPELLA", "CITTADELLA", "COLONIA", "CASETTA", "MOLO", "PRIGIONE",
  "FABBRICA", "FATTORIA", "FORTEZZA", "PORTO", "OSPEDALE", "HOTEL", "FARO",
  "MANSIONE", "MERCATO", "MINIERA", "MUSEO", "PALAZZO", "MOLO", "PORTO", "PRIGIONE",
  "PIRAMIDE", "RANCH", "ROVINE", "SCUOLA", "SANTUARIO", "STALLA", "STAZIONE",
  "TEMPIO", "TORRE", "GALLERIA", "VILLAGGIO", "MAGAZZINO", "POZZO",
  // Cibo & Bevande
  "MELA", "BACON", "PANE", "BURRO", "TORTA", "CARAMELLA", "FORMAGGIO", "CILIEGIA",
  "CIOCCOLATO", "CIDRO", "CAFFE", "PANNA", "UOVO", "UVA", "MIELE", "MARMELLATA",
  "LIMONE", "LIME", "ACERO", "MELONE", "LATTE", "MENTA", "FUNGO", "SENAPE",
  "OLIVA", "CIPOLLA", "ARANCIA", "PESCA", "PEPE", "CETRIOLO", "PRUGNA", "PATATA",
  "ZUCCA", "RISO", "SALE", "SALSA", "SPEZIA", "BISTECCA", "ZUCCHERO", "TE",
  "POMODORO", "VANIGLIA", "ACETO", "NOCE", "VINO", "LIEVITO",
  // Persone & Società
  "AGENTE", "ARCIERE", "ARTISTA", "BARONE", "CAPITANO", "CHEF", "COLONNELLO",
  "DETECTIVE", "DIPLOMATICO", "MEDICO", "DUCA", "ANZIANO", "IMPERATORE", "INGEGNERE",
  "ESPLORATORE", "GENERALE", "GUARDIA", "ARALDO", "CACCIATORE", "GIUDICE", "CAVALIERE",
  "AVVOCATO", "MERCANTE", "MONACO", "NAVIGATORE", "NOBILE", "INFERMIERE", "PILOTA",
  "PIRATA", "POETA", "PRETE", "PRINCIPE", "REGINA", "RANGER", "MARINAIO",
  "STUDIOSO", "ESPLORATORE", "SENATORE", "SCERIFFO", "SOLDATO", "CHIRURGO", "LADRO",
  "VILAIN", "MAGO",
  // Astratto & Concetti
  "ABISSO", "ETA", "ALLEANZA", "IMBOSCATA", "EQUILIBRIO", "SANGUE", "LEGAME",
  "CONFINE", "CAOS", "CODICE", "CONTRATTO", "CRISI", "MALEDIZIONE", "ALBA",
  "MORTE", "DECRETO", "ROVINA", "CREPUSCOLO", "ECO", "IMPERO", "ENIGMA",
  "ESILIO", "DESTINO", "FIAMMA", "GELO", "FANTASMA", "GLORIA", "TOMBA", "ONORE",
  "ILLUSIONE", "FERRO", "LEGGENDA", "LUCE", "COLLEGAMENTO", "MASCHERA", "MISSIONE",
  "NOTTE", "GIURAMENTO", "ORDINE", "ORIGINE", "PATTO", "PACE", "FANTASMA", "PESTE",
  "VELENO", "POTERE", "PROFEZIA", "RICERCA", "RELIQUIA", "FESSURA", "RITUALE", "RUNA",
  "CORSA", "OMBRA", "SILENZIO", "FUMO", "ANIMA", "FONTE", "TEMPESTA", "COLPO", "TRONO",
  "MAREA", "TEMPO", "TRACCIA", "PROCESSO", "VERITA", "UNIONE", "VELO", "VUOTO",
  "GUERRA", "OROLOGIO", "VENTO", "ZONA"
] as const;

export type ItWord = (typeof IT_WORDS)[number];
