/**
 * Latvian word list for ClueGrid.
 * 260+ common nouns suitable for a word-deduction game.
 */
export const LV_WORDS: readonly string[] = [
  "KALNS", "UPE", "MEŽS", "TUKŠNESIS", "OKEĀNS", "SALA", "IELEJA", "KANJONS",
  "LEDĀJS", "VULKĀNS", "ALA", "PURVS", "DŽUNGĻI", "KLINTS", "RIFS", "KĀPA",
  "PĻAVA", "ŪDENSKRITUMS", "EZERS", "ZVAIGZNE", "SAULE", "MĒNESS", "MĀKONIS", "LIETUS",
  "VĒJŠ", "UGUNS", "ZEME", "AKMENS", "KOKS", "ZIEDS", "ZĀLE", "LAPA",
  "SĒKLA", "SMILTIS", "VILNIS", "LAUVA", "TĪĢERIS", "LĀCIS", "VILKS", "LAPSA",
  "BRIEDIS", "AĻNIS", "TRUSIS", "PELE", "VĀVERE", "ZILONIS", "KAMELIS", "MĒRKAĶIS",
  "ŽIRAFA", "KENGURS", "ZIRGS", "GOVS", "AITA", "CŪKA", "SUNS", "KAĶIS",
  "ĒRGLIS", "SAKALS", "PŪCE", "PAPAGAILIS", "PINGVĪNS", "PĪLE", "ZIVS", "HAJS",
  "VALIS", "DELFĪNS", "ASTOŅKĀJIS", "KRABIS", "PUTNS", "ZIRNEKLIS", "BITE", "TAURENIS",
  "SKUDRA", "KRĒSLS", "GALDS", "GULTA", "LOGS", "DURVIS", "ATSLĒGA", "SLĒDZENE",
  "PULKSTENIS", "SPOGULIS", "LAMPA", "SVECE", "GRĀMATA", "PILDSPALVA", "ZĪMULIS", "PAPĪRS",
  "TĀLRUNIS", "DATORS", "KAMERA", "TELEVĪZIJA", "RADIO", "ZVANS", "BUNGAS", "ĢITĀRA",
  "KLAVIERES", "VIJOLE", "VIRVE", "ĶĒDE", "ĀMURS", "NAGLA", "SKRŪVE", "CIRVIS",
  "ZĀĢIS", "LĀPSTA", "SLOTA", "BIRSTE", "SPAINIS", "KAROTE", "DAKŠA", "NAZIS",
  "ŠKĪVIS", "GLĀZE", "PUDELE", "TASE", "BĻODA", "ŠĶĒRES", "ADATA", "DIEGS",
  "MĀJA", "SKOLA", "SLIMNĪCA", "BIBLIOTĒKA", "MUZEJS", "VIESNĪCA", "RESTORĀNS", "BANKA",
  "BIROJS", "VEIKALS", "TIRGUS", "RŪPNĪCA", "STACIJA", "LIDOSTA", "OSTA", "PILS",
  "BAZNĪCA", "TORNIS", "TILTS", "TUNELIS", "CEĻŠ", "IELA", "PARKS", "DĀRZS",
  "SAIMNIECĪBA", "ZOODĀRZS", "CIETUMS", "TEĀTRIS", "MAIZE", "PIENS", "SIERS", "SVIESTS",
  "OLA", "GAĻA", "RĪSI", "MAKARONI", "KARTUPELIS", "TOMĀTS", "SĪPOLS", "ĶIPLOKS",
  "BURKĀNS", "ĀBOLS", "BANĀNS", "APELSĪNS", "CITRONS", "VĪNOGA", "ZEMENE", "ĶIRSIS",
  "PERSIS", "CUKURS", "SĀLS", "PIPARI", "MEDUS", "ŪDENS", "TĒJA", "KAFIJA",
  "SULA", "ALUS", "VĪNS", "ĀRSTS", "MEDMĀSA", "SKOLOTĀJS", "SKOLNIEKS", "PILOTS",
  "VADĪTĀJS", "JŪRNIEKS", "KAREIVIS", "POLICISTS", "UGUNSDZĒSĒJS", "KARALIS", "KARALIENE", "PRINCIS",
  "AKTIERIS", "DZIEDĀTĀJS", "MĀKSLINIEKS", "RAKSTNIEKS", "PAVĀRS", "MAIZNIEKS", "ZEMNIEKS", "JURISTS",
  "TIESNESIS", "PRIESTERIS", "DRAUGS", "ĢIMENE", "TĒVS", "MĀTE", "BĒRNS", "BRĀLIS",
  "MĀSA", "VĪRIETIS", "SIEVIETE", "GALVA", "MATI", "ACS", "AUSS", "DEGUNS",
  "MUTE", "ZOBS", "ROKA", "KĀJA", "SIRDS", "ASINIS", "ĶERMENIS", "DVĒSELE",
  "ZELTS", "SUDRABS", "DZELZS", "VARŠ", "STIKLS", "PLASTMASA", "KOKSNE", "METĀLS",
  "KRĀSA", "RĪTS", "DIENA", "VAKARAS", "NAKTIS", "NEDĒĻA", "MĒNESIS", "GADS",
  "GADALAIKS", "PAVASARIS", "VASARA", "RUDENS", "ZIEMA", "ROBEŽA", "KARŠ", "MIERS",
  "UZVARA", "ZAUDĒJUMS", "SPĒLE", "BUMBA", "VAIROGS", "BULTA", "ZOBENS", "KAPS",
  "KAROGS", "KARTE", "KOMPASS", "KRONIS", "TRONIS", "STATUJA", "KRISTĀLS", "DIMANTS"
] as const;

export type LvWord = (typeof LV_WORDS)[number];
