/**
 * Romanian word list for ClueGrid.
 * 200+ common nouns in Romanian suitable for a word-deduction game.
 */
export const RO_WORDS: readonly string[] = [
  // Natura & Mediu
  "MUNTE", "RAU", "PADURE", "DESERT", "OCEAN", "INSULA", "CANION", "GHETAR",
  "VULCAN", "PESTERA", "VALE", "MLASTINA", "JUNGLE", "STANCA", "RECIF", "DUNA",
  "PAJISTE", "CASCADA", "GHEIZER", "LAGUNA", "TUNDRA", "SAVANA", "ALTOPIAN",
  // Animale
  "RECHIN", "VULTUR", "LEU", "LUP", "URS", "SOIM", "COBRA", "PANTERA",
  "BALENA", "CRAB", "MOLE", "PAPAGAL", "CALMAR", "BIZON", "RAS", "VIDRA",
  "STARC", "CERB", "FOCA", "CORB", "VULPE", "BUFNETA", "ELAN", "PINGUIN",
  "SCORPION", "GANDAC", "PITON", "BIVOL", "CAMELEON", "MORS",
  // Obiecte & Instrumente
  "ANCORA", "NICOVALA", "SAGEATA", "TOPOR", "BUTOI", "CLOPOT", "LAMA", "SURUB",
  "POD", "PERIE", "GALEATA", "TUN", "LANT", "COS", "CEAS",
  "COMPAS", "COROANA", "CRISTAL", "PUMNAL", "TOBA", "GARD", "FLACON", "POARTA",
  "CIOCAN", "CARLIG", "CORN", "JARI", "CHEIE", "FELINAR", "LACAT",
  "OGLINDA", "RETEA", "AC", "SFERA", "TUB", "PRISMA", "SCRIPETE", "POMPA",
  "FRANGHIE", "VELA", "SCUT", "SITA", "CUI", "ARC", "TOIAG", "STAMPILA",
  "STATUIE", "SABIE", "TORTA", "CAPCANA", "SEIF", "VAGON", "ROATA", "FLUIER",
  "FIR", "CHEIE", "SCANDURA", "LOPATA", "DALT", "PISTON",
  // Locuri & Structuri
  "ABATIE", "ARENA", "POD", "BANCA", "SURA", "BAZAR", "BUNKER", "CASTEL",
  "PIVNITA", "CAPELA", "CITADELA", "COLONIE", "CABANA", "MOLO", "TEMNITA",
  "FABRICA", "FERMA", "FORTAREATA", "PORT", "SPITAL", "HOTEL", "FAR",
  "MANAC", "PIATA", "MINA", "MUZEU", "PALAT", "MOLO", "PORT", "INCHISOARE",
  "PIRAMIDA", "RANCH", "RUINE", "SCOALA", "SANCTUAR", "GRAJD", "STATIE",
  "TEMPLU", "TURN", "TUNEL", "SAT", "DEPOZIT", "FANTANA",
  // Mancare & Bautura
  "MAR", "BACON", "PAINE", "UNT", "TORT", "BOMBOANA", "BRANZA", "CIREASA",
  "CIOCOLATA", "CIDRU", "CAFEA", "FRISCA", "OU", "STRUGURE", "MIERE", "GEM",
  "LAMAIE", "LIME", "ARTAR", "PEPENE", "LAPTE", "MENTA", "CIUPERCA", "MUSTAR",
  "MASLINA", "CEAPA", "PORTOCALA", "PIERSICA", "PIPER", "CASTRAVETE", "PRUNA", "CARTOF",
  "DOVLEAC", "OREZ", "SARE", "SOS", "CONDIMENT", "FRIPTURA", "ZAHAR", "CEAI",
  "ROSIE", "VANILIE", "OTET", "NUCA", "VIN", "DROJDIE",
  // Oameni & Societate
  "AGENT", "ARCAS", "ARTIST", "BARON", "CAPITAN", "BUCATAR", "COLONEL",
  "DETECTIV", "DIPLOMAT", "MEDIC", "DUCE", "BATRAN", "IMPARAT", "INGINER",
  "EXPLORATOR", "GENERAL", "GARDA", "HERALD", "VANATOR", "JUDECATOR", "CAVALER",
  "AVOCAT", "NEGUSTOR", "CALUGAR", "NAVIGATOR", "NOBIL", "ASISTENTA", "PILOT",
  "PIRAT", "POET", "PREOT", "PRINT", "REGINA", "RANGER", "MARINAR",
  "SAVANT", "SCOUT", "SENATOR", "SERIF", "SOLDAT", "CHIRURG", "HOT",
  "TALHAR", "VRAJITOR",
  // Concepte & Abstracte
  "ABIS", "VARSTA", "ALIANTA", "AMBUSCADA", "ECHILIBRU", "SANGE", "LEGATURA",
  "GRANITA", "CAOS", "COD", "CONTRACT", "CRIZA", "BLESTEM", "ZORI",
  "MOARTE", "DECRET", "PIERZANIE", "ECOU", "IMPERIU", "ENIGMA",
  "EXIL", "DESTIN", "FLACARA", "INGHET", "FANTASMA", "GLORIE", "MORMANT", "ONOARE",
  "ILUZIE", "FIER", "LEGENDA", "LUMINA", "LEGATURA", "MASCA", "MISIUNE", "NOAPTE",
  "JURAMANT", "ORDIN", "ORIGINE", "PACT", "PACE", "FANTOMA", "CIUMA", "OTRAVA",
  "PUTERE", "PROFETIE", "MISIUNE", "RELICVA", "FALIE", "RITUAL", "RUNA", "ASALT",
  "UMBRA", "TACERE", "FUM", "SUFLET", "SURSA", "FURTUNA", "LOVITURA", "TRON", "MAREE",
  "TIMP", "URMA", "PROCES", "ADEVAR", "UNIUNE", "VAL", "VID", "RAZBOI",
  "CEAS", "VANT", "ZONA"
] as const;

export type RoWord = (typeof RO_WORDS)[number];
